variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: "$CI_PROJECT_PATH"
  paths:
    - node_modules/

before_script:
  - npm i

stages:
  - build

job_build:
  stage: build
  only:
    - tags
    - api
    - external
    - pipelines
    - schedules
    - triggers
    - web
  script:
    - npm run build
    - cd dist
    - ftp -n <<EOF
    - open $FTP_HOST
    - user $FTP_USER $FTP_PWD
    - binary
    - hash
    - cd $CI_PROJECT_PATH
    - prompt
    - mput "*.tar.gz"
    - close
    - bye
    - EOF
